galaxy_info:
  author: daos-stack
  description: Installs IO500 benchmark scripts
  company: Intel Corporation
  issue_tracker_url: https://daosio.atlassian.net/jira/software/c/projects/DAOS/issues

  license: Apache-2.0

  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags: []

dependencies: []
