---

- name: Converge
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "Include daos role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
