# tasks file for selinux

- name: Stat /etc/selinux/config
  ansible.builtin.stat:
    path: /etc/selinux/config
  register: selinux_config_file

- name: Disable selinux
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX={{ selinux_state }}"
  when: selinux_config_file.stat is defined and selinux_config_file.stat.exists
  register: selinux_config_state

- name: Create /etc/ansible/reboot file
  when: selinux_config_state.changed
  block:
    - name: Create /etc/ansible directory
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create file used by reboot role to trigger a reboot
      ansible.builtin.file:
        path: /etc/ansible/reboot
        state: touch
        mode: '0644'
