---
# tasks file for epel

- name: Include install.yml for epel
  ansible.builtin.include_tasks: install.yml
  when: ansible_os_family | lower == "redhat"
  args:
    apply:
      tags:
        - epel
  tags:
    - epel
