---
collections:
  - src: https://github.com/mark-olson
    name: ansible-collection-daos
    type: git
    version: develop

# To install this collection
# ansible-galaxy collection install git+https://github.com/mark-olson/ansible-collection-daos.git,develop
