---
collections:
  - src: https://github.com/daos-stack
    name: ansible-collection-daos
    type: git
    version: develop

# To install this collection
# ansible-galaxy collection install git+https://github.com/daos-stack/ansible-collection-daos.git,develop
