---
# installation tasks for packages

- name: Install common packages
  ansible.builtin.package:
    name: "{{ packages_common }}"
    state: present
  when: packages_install_common

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ packages_additional }}"
    state: present
  when: packages_install_additional
