---
#
# OS specific vars for the reboot role
#

# There is no need to install anything for suse because zypper has the ps
# command which does the same thing as the 'needrestart' command.
_reboot_packages:
  default: []
  centos_7:
    - yum-utils
  centos_8:
    - dnf-utils
  debian:
    - needrestart
    - needrestart-session

reboot_packages: '{{ _reboot_packages[ansible_distribution|lower ~"_"~ ansible_distribution_version] |
  default(_reboot_packages[ansible_distribution|lower ~"_"~ ansible_distribution_major_version] |
  default(_reboot_packages[ansible_distribution|lower] |
  default(_reboot_packages[ansible_os_family|lower] |
  default(_reboot_packages["default"])))) }}'
