---
# handlers file for daos

# If the daos_server service is restarted, then all daos_agent services should
# be restarted.
- name: restart daos_server service
  ansible.builtin.service:
    name: daos_server
    state: restarted
  when: daos_role_server in daos_roles
  notify: restart daos_agent service
  tags: all

- name: restart daos_agent service
  ansible.builtin.service:
    name: daos_agent
    state: restarted
  when: daos_role_client in daos_roles
  tags: all
