---
- name: daos_client | Install and configure DAOS client
  hosts: "{{ target | default('localhost') }}"
  gather_facts: true

  vars:
    az_subscription: "{{ subscription | default(lookup('env', 'DAOS_AZ_CORE_ACCT_NAME')) | default('daos-rg') }}"
    az_group_name: "{{ group_name | default(lookup('env', 'DAOS_AZ_CORE_RG_NAME')) | default('daos-rg') }}"
    az_location: "{{ location | default('DAOS_AZ_CORE_LOCATION') | default('') }}"
    az_vault_name: "{{ vault_name | default(lookup('env', 'DAOS_AZ_ARM_KEY_VAULT_NAME')) | default('') }}"
    az_server_host_list: "{{ server_host_list | default([]) }}"

  tasks:
    - name: DEBUG az_subscription
      debug:
        var: az_subscription

    - name: daos_client | Import selinux role
      import_role:
        name: daos_stack.daos.selinux

    - name: daos_client | Import packages role
      import_role:
        name: daos_stack.daos.packages

    - name: daos_client | Import tune role
      import_role:
        name: daos_stack.daos.tune

    - name: daos_client | Import azurecli role
      import_role:
        name: daos_stack.daos.azurecli
      vars:
        azurecli_do_login: true
        azurecli_login_method: "identity"
        azurecli_default_subscription: "{{ az_subscription }}"
        azurecli_default_group: "{{ az_group_name }}"
        azurecli_default_az_location: "{{ az_location }}"

    - name: daos_client | Add localhost to the inventory groups
      add_host:
        name: localhost
        groups: "{{ item }}"
      loop:
        - daos_admins
        - daos_clients
      delegate_to: localhost
      run_once: true
      changed_when: false

    - name: daos_client | Import daos role
      import_role:
        name: daos_stack.daos.daos
      vars:
        daos_roles:
          - admin
          - client
        daos_deploy_certs: false
        daos_do_install: true
        daos_do_configuration: true
        daos_do_cert_gen: false
        daos_do_start_services: false
        daos_transport_config_allow_insecure: false
        daos_server_host_list: "{{ az_server_host_list | list }}"
        daos_access_points: "{{ az_server_host_list | list | daos_stack.daos.daos_access_points }}"

    - name: daos_client | Import daos_certs role
      import_role:
        name: daos_certs
      vars:
        daos_certs_store_type: azure_key_vault
        daos_certs_az_vault_name: "{{ az_vault_name }}"
        daos_certs_store_push_enabled: false
        daos_certs_store_pull_enabled: true

    - name: daos_client | Ensure daos_agent service is started
      ansible.builtin.service:
        name: daos_agent
        state: started

    - name: daos_client | Import powertools role
      import_role:
        name: daos_stack.daos.powertools

    - name: daos_client | Import inteloneapi role
      import_role:
        name: daos_stack.daos.inteloneapi

    - name: daos_client | Import io500 role
      import_role:
        name: daos_stack.daos.io500
