galaxy_info:
  author: mark-olson
  description: Role to install DAOS
  company: Intel Corporation
  issue_tracker_url: https://daosio.atlassian.net/jira/software/c/projects/DAOS/issues
  license: Apache-2.0
  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - daos
    - storage

dependencies: []
