---
galaxy_info:
  role_name: inteloneapi
  author: daos-stack
  description: Role that installs the Intel OneAPI repository and the MPI packages
  company: Intel Corporation

  license: Apache-2.0

  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags: []

dependencies: []
