---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy

# scenario:
#   create_sequence:
#     - dependency
#     - create
#     - prepare
#   check_sequence:
#     - dependency
#     - cleanup
#     - destroy
#     - create
#     - prepare
#     - converge
#     - check
#     - destroy
#   converge_sequence:
#     - dependency
#     - create
#     - prepare
#     - converge
#   destroy_sequence:
#     - dependency
#     - cleanup
#     - destroy
#   test_sequence:
#     - dependency
#     - cleanup
#     - destroy
#     - syntax
#     - create
#     - prepare
#     - converge
#     - idempotence
#     - side_effect
#     - verify
#     - cleanup
#     - destroy
