---
# redhat OS family tasks for io500

- name: install_redhat | Install the 'Development tools' group
  ansible.builtin.package:
    name: "@Development tools"
    state: present

- name: install_redhat | Install dependecies
  ansible.builtin.package:
    name: "{{ io500_dep_pkgs }}"
    state: present

- name: install_redhat | Install daos-devel
  ansible.builtin.package:
    name: "daos-devel"
    state: present

- name: Clone IO500 repo
  ansible.builtin.git:
    repo: https://github.com/IO500/io500.git
    dest: "{{ io500_path }}"
    version: "{{ io500_version }}"
    force: true

- name: Run prepare.sh script
  ansible.builtin.shell: |
    export I_MPI_OFI_LIBRARY_INTERNAL=0
    export I_MPI_OFI_PROVIDER="tcp;ofi_rxm"
    source /opt/intel/oneapi/setvars.sh
    "{{ io500_path }}/prepare.sh"
  args:
    chdir: "{{ io500_path }}"
    executable: /bin/bash

- name: Copy run_io500.sh script
  ansible.builtin.template:
    src: run_io500.sh.j2
    dest: "{{ io500_run_io500_path }}"
    owner: daos_admin
    group: daos_admin
    mode: '0755'
