---
# Intel oneAPI install tasks for io500

- name: Import GPG key for Intel oneAPI repo
  ansible.builtin.rpm_key:
    key: "{{ io500_oneapi_gpgkey_url }}"
    state: present

- name: Create Intel oneAPI repo file
  ansible.builtin.template:
    src: "etc/yum.repos.d/oneAPI.repo.j2"
    dest: "{{ io500_oneapi_repo_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Install Intel oneAPI MPI
  ansible.builtin.package:
    name: "{{ io500_oneapi_pkgs }}"
    state: present
