---
# redhat OS family tasks for io500

- name: install_redhat | Copy io500 scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ io500_dir }}"
    owner: "{{ io500_user }}"
    group: "{{ io500_user }}"
    mode: '0755'
  loop:
    - io500_install.sh
    - io500_run.sh

- name: install_redhat | Copy io500.env file
  ansible.builtin.copy:
    src: "io500.env"
    dest: "{{ io500_dir }}"
    owner: "{{ io500_user }}"
    group: "{{ io500_user }}"
    mode: '0644'

- name: install_redhat | Run io500_install.sh
  ansible.builtin.command: "{{ io500_dir }}/io500_install.sh"
  args:
    creates: "{{ io500_install_dir }}/io500"

- name: install_redhat | Copy config-full.ini.envtpl
  ansible.builtin.copy:
    src: "{{ io500_version }}.config-full.ini.envtpl"
    dest: "{{ io500_install_dir }}/{{ io500_version }}.config-full.ini.envtpl"
    owner: "root"
    group: "root"
    mode: '0644'
