---
# tasks file for io500

- name: main | Include distro family specific install.yml
  ansible.builtin.include_tasks: '{{ io500_install_task_file }}'
  args:
    apply:
      tags:
        - io500
        - io500_install
  tags:
    - io500
    - io500_install
