---
# vars file for powertools

_powertools_repo_name:
  redhat: powertools
  almalinux_9: crb

powertools_repo_name: "{{ _powertools_repo_name[ansible_distribution | lower ~ '_' ~ ansible_distribution_major_version] | default(
                          _powertools_repo_name[ansible_distribution | lower ] ) | default(
                          _powertools_repo_name[ansible_os_family | lower ] ) }}"

_powertools_repo_file:
  redhat: "{{ ansible_distribution }}-PowerTools.repo"
  rocky: "{{ ansible_distribution }}-PowerTools.repo"
  almalinux_8: "almalinux-powertools.repo"
  almalinux_9: "almalinux-crb.repo"
  centos: "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-PowerTools.repo"

powertools_repo_file: "{{ _powertools_repo_file[ansible_distribution | lower ~ '_' ~ ansible_distribution_major_version] | default(
                          _powertools_repo_file[ansible_distribution | lower ] ) | default(
                          _powertools_repo_file[ansible_os_family | lower ] ) }}"
