---
# DAOS server node configuration tasks for the daos role

- name: Create daos_server.yml file
  ansible.builtin.template:
    src: 'etc/daos/{{ daos_config_version }}/daos_server.yml.j2'
    dest: '/etc/daos/daos_server.yml'
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart daos_server service

# If iommu is not enabled, then the daos_server service must run as root.
- name: Set user and group in daos_server service
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/daos_server.service
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop:
     - { key: "User", value: "{{ ansible_local.daos.iommu_enabled | ternary(daos_server_user, 'root') }}" }
     - { key: "Group", value: "{{ ansible_local.daos.iommu_enabled | ternary(daos_server_user, 'root') }}" }
  register: daos_server_service_file

- name: Re-read systemd service files
  ansible.builtin.systemd:
    daemon_reload: yes
  when: daos_server_service_file.changed
