---
# installation tasks file for daos on RedHat family distros

- name: Create repo file
  ansible.builtin.template:
    src: 'repofiles/daos.repo.{{ ansible_pkg_mgr }}.j2'
    dest: '{{ daos_repo_files_dir }}/daos.repo'
    owner: root
    group: root
    mode: '0644'

- name: Install dependent packages
  ansible.builtin.package:
    name: '{{ daos_dep_pkgs }}'
    state: present

- name: Install DAOS packages
  ansible.builtin.package:
    name: '{{ daos_pkgs[item] | default([]) }}'
    state: present
  loop: '{{ daos_roles }}'

- name: Create daos server log directory
  ansible.builtin.file:
    path: "{{ daos_server_log_dir }}"
    state: directory
    owner: "{{ daos_server_user }}"
    group: "{{ daos_server_user }}"
    mode: '0755'
  when: '"server" in daos_roles'

- name: Enable daos_server service
  ansible.builtin.service:
    name: daos_server
    enabled: true
  when: '"server" in daos_roles'

- name: Copy clean_daos_storage.sh script
  ansible.builtin.copy:
    src: clean_daos_storage.sh
    dest: /root/clean_daos_storage.sh
    owner: root
    group: root
    mode: '0750'
