---
# main tasks file for daos role

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost
  tags:
    - daos
    - daos_install
    - daos_config
    - daos_certs
    - daos_storage

- name: Install ansible facts for daos
  ansible.builtin.import_tasks: facts.yml
  tags:
    - daos
    - daos_install
    - daos_config
    - daos_certs
    - daos_storage

- name: Include distro family specific install.yml
  ansible.builtin.include_tasks:
    file: '{{ daos_install_task_file }}'
    apply:
      tags:
        - daos
        - daos_install
        - ansible_os_family | lower == "redhat" or ansible_os_family | lower == "opensuse"
  tags:
    - daos
    - daos_install

- name: Include certificate deployment tasks
  ansible.builtin.import_tasks: certs.yml
  when:
    - daos_do_cert_gen
    - ansible_os_family | lower == "redhat" or ansible_os_family | lower == "opensuse"
  tags:
    - daos
    - daos_certs

- name: Include config tasks
  ansible.builtin.import_tasks: config.yml
  when:
    - daos_do_configuration
    - ansible_os_family | lower == "redhat" or ansible_os_family | lower == "opensuse"
  tags:
    - daos
    - daos_config

- name: Include storage management tasks
  ansible.builtin.include_tasks:
    file: storage.yml
    apply:
      tags:
        - daos
        - daos_storage
  when:
    - daos_do_storage_format
    - ansible_os_family | lower == "redhat" or ansible_os_family | lower == "opensuse"
  tags:
    - daos
    - daos_storage
