---
# storage administration tasks for the daos role

- name: show IPs of all servers
  debug:
    msg: "{{ groups['daos_servers'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
  when: inventory_hostname in groups['daos_admins']

- name: show inventory_hostname
  debug:
    var: inventory_hostname
  when: inventory_hostname in groups['daos_admins']

- name: Set fact containing IPs of all servers
  ansible.builtin.set_fact:
    daos_server_ips: "{{ groups['daos_servers'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure that the daos_server service is started
  ansible.builtin.service:
    name: daos_server
    state: started
  when: daos_role_server in daos_roles

- name: Ensure that the daos_agent service is started
  ansible.builtin.service:
    name: daos_agent
    state: started
  when: daos_role_client in daos_roles

# FIX: This is very fragile.
#      https://daosio.atlassian.net/browse/DAOS-12293
- name: Determine if system is initialized
  ansible.builtin.shell: |
    if dmg system query -o {{ daos_admin_config_dir }}/daos_control.yml -v -j 2>/dev/null | jq -r '.error' | grep -q "system is uninitialized"; then
      echo true
    else
      echo false
    fi
  become_user: "{{ daos_admin_user }}"
  changed_when: false
  when: inventory_hostname == groups['daos_admins'][0]
  register: daos_format_needed

- name: DEBUG daos_format_needed
  debug:
    var: daos_format_needed

- name: DEBUG daos_do_storage_format
  debug:
    var: daos_do_storage_format

- name: DEBUG format storage when
  debug:
    msg: "{{ (inventory_hostname == groups['daos_admins'][0]) and
        (daos_do_storage_format | bool) and
        (daos_format_needed.stdout | bool) }}"

- name: Format storage
  ansible.builtin.shell: "dmg storage format -o {{ daos_admin_config_dir }}/daos_control.yml -l '{{ daos_server_ips }}'"
  become_method: su
  become_user: "{{ daos_admin_user }}"
  when: (inventory_hostname == groups['daos_admins'][0]) and
        (daos_do_storage_format | bool) and
        (daos_format_needed.stdout | bool)

- name: DEBUG number of servers
  debug:
    var: groups['daos_servers'] | length

# After running 'dmg storage format' running 'dmg system query' will block until
# the system is initialized. We should not go on until all of the servers have
# joined.
- name: Wait for system to initialize
  ansible.builtin.shell: dmg system query -o /home/daos_admin/daos/daos_control.yml -j | jq -r '.response.members[]|select(.state=="joined")|.fault_domain'
  become_method: su
  become_user: "{{ daos_admin_user }}"
  register: daos_joined_servers
  until: daos_joined_servers.stdout_lines | length == groups['daos_servers'] | length
  delay: 5
  retries: 10
  when: inventory_hostname == groups['daos_admins'][0]
  changed_when: false

- name: Create pools
  ansible.builtin.shell: |
    if [[ ! $(dmg pool list -o /home/daos_admin/daos/daos_control.yml -j | jq -r '.response.pools[] | select(.label=="{{ pool.label }}") | .label') == "io500_pool" ]]; then
      dmg pool create -o {{ daos_admin_config_dir }}/daos_control.yml -z {{ pool.size }} -t {{ pool.tier_ratio }} -u {{ pool.user }} --label="{{ pool.label }}"
      dmg pool set-prop "{{ pool.label }}" -o {{ daos_admin_config_dir }}/daos_control.yml --name=reclaim --value=disabled
      {% for acl in pool.acls %}
        dmg pool update-acl -o {{ daos_admin_config_dir }}/daos_control.yml -e "{{ acl }}" {{ pool.label }}
      {% endfor %}
    fi
  become_method: su
  become_user: "{{ daos_admin_user }}"
  when: inventory_hostname == groups['daos_admins'][0]
  changed_when: false
  loop: "{{ daos_pools }}"
  loop_control:
    loop_var: pool
