---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Assert true for non-redhat distros
      ansible.builtin.assert:
        that: true
      when: ansible_os_family | lower != "redhat"

    - name: Check if epel repo is enabled
      block:
        - name: Get EPEL repo info
          yum_repository:
            name: epel
            state: present
          register: epel_repo_info

        - name: Assert EPEL is enabled
          ansible.builtin.assert:
            that:
              - "epel_repo_info.repo.enabled"
            fail_msg: "EPEL repository is not enabled"
      when: ansible_os_family | lower == "redhat"
