---
#
# custom facts for tune role
#

- name: Create facts directory
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create tune facts script
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/tune.fact.j2'
    dest: '/etc/ansible/facts.d/tune.fact'
    owner: root
    group: root
    mode: '0755'
  register: tune_fact_script

- name: Reload facts
  ansible.builtin.setup:
    filter: ansible_local
  when: tune_fact_script.changed  # noqa: false-handler
