---
# tasks to disable selinux

- name: Disable selinux
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  register: tune_selinux_config

- name: Create /etc/ansible/reboot file
  when: tune_selinux_config.changed
  block:
    - name: Create /etc/ansible directory
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create file used by reboot role to trigger a reboot
      ansible.builtin.file:
        path: /etc/ansible/reboot
        state: touch
        mode: '0644'
