---
# playbook:     daos_cluster.yml
# playbook_fqn: daos_stack.daos.daos_cluster

- name: daos_cluster | Wait for hosts
  hosts: all
  gather_facts: false
  become: false
  any_errors_fatal: true

  tasks:
    - name: daos_cluster | Wait for hosts to become ready
      block:
        - name: daos_cluster | Wait for port to be available
          ansible.builtin.wait_for:
            port: "{{ ansible_port | default('22') }}"
            timeout: 600
          become: false
          changed_when: false
          when: ansible_connection is defined

        - name: daos_cluster | Test connection
          ansible.builtin.wait_for_connection:
            timeout: 300
          changed_when: false

        - name: daos_cluster | Test sudo
          ansible.builtin.command:
            cmd: sudo --version
          changed_when: false

      rescue:
        - name: daos_cluster | Unable to continue
          ansible.builtin.debug:
            msg: "One or more hosts are not available. Cannot continue."

        - name: daos_cluster | End play
          ansible.builtin.meta: end_play


- name: daos_cluster | DAOS cluster prep
  hosts: all
  gather_facts: true
  become: true

  roles:
    - role: daos_stack.daos.selinux
    - role: daos_stack.daos.epel
    - role: daos_stack.daos.packages
    - role: daos_stack.daos.tune
    - role: daos_stack.daos.reboot
      when: inventory_hostname not in groups['daos_admins']


- name: daos_cluster | DAOS cluster installation and configuration
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: daos_cluster | Create access_points group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: access_points
      when: hostvars[item].is_access_point | default(false) | bool
      with_items: "{{ groups['daos_servers'] }}"
      changed_when: false
      tags: always

    - name: daos_cluster | Create daos_access_points IP list
      ansible.builtin.set_fact:
        daos_access_points: "{{ groups.access_points |
          map('extract', hostvars, 'ansible_default_ipv4') |
          map(attribute='address') | list }}"
      tags: always

  roles:
    - role: daos_stack.daos.daos
