---
# playbook:     daos.yml
# playbook_fqn: daos_stack.daos.daos

- name: Install DAOS
  hosts: "{{ target_hosts | default('localhost') }}"
  gather_facts: true
  become: true
  any_errors_fatal: true

  roles:
    - role: daos_stack.daos.selinux
    - role: daos_stack.daos.epel
    - role: daos_stack.daos.packages
    - role: daos_stack.daos.tune
    - role: daos_stack.daos.daos
