---
# playbook:     io500_install.yml
# playbook_fqn: daos_stack.daos.io500_install

- name: IO500 installation
  hosts: "{{ target_hosts | default('None') }}"
  gather_facts: true
  become: true

  roles:
    - role: daos_stack.daos.epel
    - role: daos_stack.daos.packages
    - role: daos_stack.daos.io500
