---
- name: Test
  hosts: all
  gather_facts: true
  become: true

  # tasks:
  #   - name: Debug
  #     ansible.builtin.debug:
  #       msg: "daos_repo_base_url={{ daos_repo_base_url }}"

  roles:
    - role: daos_stack.daos.selinux
    - role: daos_stack.daos.epel
    - role: daos_stack.daos.packages
    - role: daos_stack.daos.tune
    - role: daos_stack.daos.daos
    - role: daos_stack.daos.inteloneapi
    - role: daos_stack.daos.io500
